using System;
using System.Collections.Generic;

namespace StarTrek_KG
{
    public class Constants
    {
        //Title by Joshua Bell, Enterprise by Unknown, modified by Kevin Gabbert
        public static readonly string[] APP_TITLE = {
                                                        @"     ________________ _     _____      _______________      ______ ___   ___"
                                                        ,
                                                        @"   ,' ________   ___// \    \  __ \   /___   ___/\  __ \   / ____/ \ /  ,' /"
                                                        ,
                                                        @"  |  `-.__    | |   / . \   | | / /       | |    | | / /  | /____  | | / .'"
                                                        ,
                                                        @"   `-.___ `.  | |  / /_\ \  |  _ `.       | |    |  _ `.  | ____/  |  _ `."
                                                        ,
                                                        @"  _______\  \ | | / _____ \ | | `. \_     | |    | | `. \_| \____  | | `. \____"
                                                        ,
                                                        @" /___________|/_|/_/     \_\|_\  /__/     /_\    |_\  /__/ `.____| |_\   /_____\"
                                                        ,
                                                        @"",
                                                        @"                       _________________        _",
                                                        @"                       \-__(=======//o)/____.--'-`--.___",
                                                        @"                                  \ \  `,--,--.___.-----'",
                                                        @"                                .--`\\-'-==",
                                                        @"                               '--.______.|]"
                                                    };

        public const string EMPTY = "   ";
        public const string ENTERPRISE = "<*>";
        public const string HOSTILE = "+++";
        public const string STARBASE = ">!<";
        public const string STAR = " * ";
        //public const string ALLY = "<++>";

        public static int SECTOR_MIN; 
        public static int SECTOR_MAX; 

        public static int QUADRANT_MIN; 
        public static int QUADRANT_MAX;

        public static int SHIELDS_DOWN_LEVEL;
        public static int LOW_ENERGY_LEVEL;

        public const int MOVEMENT_PRECISION = 1000;

        public static List<String> MAP_DIRECTION = new List<String>(){ "n", "ne", "e", "se", "s", "sw", "w", "nw" };

        #region QuadrantNames

        #endregion

        #region KlingonShipNames

        //todo: pull these from app.config
        public static readonly string[] KLINGON_SHIP_NAMES = {
                                                                 "IKC Aktuh",
                                                                 "IKC Amar",
                                                                 "IKC Azetbur",
                                                                 "IKC B'iJik",
                                                                 "IKC BIrHegh",
                                                                 "IKC BIrHom",
                                                                 "IKC BIrruv",
                                                                 "IKC BIvwI",
                                                                 "IKC BochbaS",
                                                                 "IKC BochHeH",
                                                                 "IKC BochHov",
                                                                 "IKC BochlIy",
                                                                 "IKC Bochqu",
                                                                 "IKC Bochtev",
                                                                 "IKC BoHcha",
                                                                 "IKC BoHDegh",
                                                                 "IKC BoHDol",
                                                                 "IKC BoHDuS",
                                                                 "IKC BoHpeng",
                                                                 "IKC BoHtIq",
                                                                 "IKC BoHyaS",
                                                                 "IKC BoQwI'",
                                                                 "IKC Boreth",
                                                                 "IKC Bortas",
                                                                 "IKC BoSwI'",
                                                                 "IKC BotwI'",
                                                                 "IKC B'rel",
                                                                 "IKS B'Moth",
                                                                 "IKC Buruk",
                                                                 "IKC BuvwI'",
                                                                 "IKC Chang",
                                                                 "IKC CharghwI'",
                                                                 "IKC ChavwI'",
                                                                 "IKC ChelwI'",
                                                                 "IKC ChenwI'",
                                                                 "IKC ChoHwI'",
                                                                 "IKC ChopwI'",
                                                                 "IKC ChovwI'",
                                                                 "IKS Ch'Tang",
                                                                 "IKC ChungwI'",
                                                                 "IKC Chu'wI'",
                                                                 "IKC DajDuS",
                                                                 "IKC Dajghol",
                                                                 "IKC Dajghu'",
                                                                 "IKC DaqwI'",
                                                                 "IKC DighreS",
                                                                 "IKC Divok",
                                                                 "IKC Dochbeq",
                                                                 "IKC Dochqup",
                                                                 "IKC DojHoH",
                                                                 "IKC DojqIvon",
                                                                 "IKC Dojquv",
                                                                 "IKC Dojvan",
                                                                 "IKC DoqbaS",
                                                                 "IKC Doqcha",
                                                                 "IKC DoqghuH",
                                                                 "IKC DoqHegh",
                                                                 "IKC DoqHo'",
                                                                 "IKC DoqmaS",
                                                                 "IKC Doqram",
                                                                 "IKC Drovna",
                                                                 "IKC DughDuy",
                                                                 "IKC Dughjup",
                                                                 "IKC Dughla'",
                                                                 "IKC DughQu'",
                                                                 "IKC Dughro'",
                                                                 "IKC DughwoQ",
                                                                 "IKC DughyaS",
                                                                 "IKC DujqaD",
                                                                 "IKC DujQeH",
                                                                 "IKC Erikang",
                                                                 "IKC Etam",
                                                                 "IKC Fek'lhr",
                                                                 "IKC GhoHwI'",
                                                                 "IKC GhorwI'",
                                                                 "IKC GhuHwI'",
                                                                 "IKC GhungDol",
                                                                 "IKC Ghunglom",
                                                                 "IKC GhungQa'",
                                                                 "IKC GhungQogh",
                                                                 "IKC Gi'ral",
                                                                 "IKC Gorkon",
                                                                 "IKS Gr'oth",
                                                                 "IKC Gre'thor",
                                                                 "IKC Hegh'ta",
                                                                 "IKC HeghwI'",
                                                                 "IKC Hembu'",
                                                                 "IKC HemDuy",
                                                                 "IKC Hemghol",
                                                                 "IKC Hemlom",
                                                                 "IKC HeQwI'",
                                                                 "IKC HIvwI'",
                                                                 "IKC HoSbatlh",
                                                                 "IKC HoSbegh",
                                                                 "IKC HoSDuj",
                                                                 "IKC HoSjagh",
                                                                 "IKC HoSloD",
                                                                 "IKC HoSmu'",
                                                                 "IKC HoSqempa'",
                                                                 "IKC Hovpeng",
                                                                 "IKC HubwI'",
                                                                 "IKC HujwI'",
                                                                 "IKC HurghSan",
                                                                 "IKC Husghaj",
                                                                 "IKC Jaqbeq",
                                                                 "IKC Jaqbutlh",
                                                                 "IKC JaqDup",
                                                                 "IKC JaqHoq",
                                                                 "IKC JaqtIq",
                                                                 "IKC JaqwI'",
                                                                 "IKC J'Ddanv",
                                                                 "IKC JonwI'",
                                                                 "IKC Kahless",
                                                                 "IKC Kang",
                                                                 "IKC Kardasz",
                                                                 "IKC K'Ehleyr",
                                                                 "IKC Khitomer",
                                                                 "IKC Kirom",
                                                                 "IKC Klag",
                                                                 "IKS Klothos",
                                                                 "IKC K'mpec",
                                                                 "IKC K'nera",
                                                                 "IKC Koloth",
                                                                 "IKC Konmel",
                                                                 "IKC Koord",
                                                                 "IKC Kor",
                                                                 "IKS Koraga",
                                                                 "IKC Korinar",
                                                                 "IKC Korris",
                                                                 "IKC K'Ratak",
                                                                 "IKC Kri'stak",
                                                                 "IKC Kruge",
                                                                 "IKC K'Temoc",
                                                                 "IKC K't'inga",
                                                                 "IKC Kurn",
                                                                 "IKC K'Vort",
                                                                 "IKC Le'batlh",
                                                                 "IKC Le'chav",
                                                                 "IKC Le'Hov",
                                                                 "IKC Le'qorDu'",
                                                                 "IKC LI'wI'",
                                                                 "IKC LoHwI'",
                                                                 "IKC Lorgh",
                                                                 "IKC Lursor",
                                                                 "IKS Maht-H'a",
                                                                 "IKS Malpara",
                                                                 "IKC Maltz",
                                                                 "IKC M'Char",
                                                                 "IKC Melota",
                                                                 "IKC MeQwI'",
                                                                 "IKC MIywI'",
                                                                 "IKC MobwI'",
                                                                 "IKC MolwI'",
                                                                 "IKC Morath",
                                                                 "IKC Morska",
                                                                 "IKC Mulbe'Hom",
                                                                 "IKC Mulchom",
                                                                 "IKC Mullagh",
                                                                 "IKC MulQogh",
                                                                 "IKC MulSaj",
                                                                 "IKC Mulyagh",
                                                                 "IKC MulyaS",
                                                                 "IKS Nardiv",
                                                                 "IKC NajwI'",
                                                                 "IKC NaSbutlh",
                                                                 "IKC NaSDol",
                                                                 "IKC NaSDup",
                                                                 "IKC NaSgho",
                                                                 "IKC NaSghong",
                                                                 "IKC NaStaj",
                                                                 "IKC Negh'Var",
                                                                 "IKC NgIlwI'",
                                                                 "IKC Ngojcha",
                                                                 "IKC NgojDegh",
                                                                 "IKC NgojDol",
                                                                 "IKC NgojDuS",
                                                                 "IKC Ngojpeng",
                                                                 "IKC Ngojporgh",
                                                                 "IKC NgongwI'",
                                                                 "IKC Ngotlhbe'",
                                                                 "IKC NgotlhchoH",
                                                                 "IKC NgotlhDa'",
                                                                 "IKC NgotlhDol",
                                                                 "IKC Ngotlhpuq",
                                                                 "IKS Ning'tao",
                                                                 "IKC NIvDup",
                                                                 "IKC Niv'etlh",
                                                                 "IKC Nivjech",
                                                                 "IKC NIvleSSov",
                                                                 "IKC Nivqempa'",
                                                                 "IKC NIvQu'",
                                                                 "IKC Nivta'",
                                                                 "IKC No'Mat",
                                                                 "IKC Noycha'puj",
                                                                 "IKC NoyDaS",
                                                                 "IKC NoyDuj",
                                                                 "IKC Noyqech",
                                                                 "IKC NoyvI'",
                                                                 "IKC Nu'Daq",
                                                                 "IKC NuQwI'",
                                                                 "IKS Orantho",
                                                                 "IKC Pagh",
                                                                 "IKC PejwI'",
                                                                 "IKC P'Rang",
                                                                 "IKC Praxis",
                                                                 "IKC QabwI'",
                                                                 "IKC QaDwI'",
                                                                 "IKC QaHwI'",
                                                                 "IKC QalIa'pe'",
                                                                 "IKC Qanmang",
                                                                 "IKC Qanvaj",
                                                                 "IKC QarbeH",
                                                                 "IKC QarchetvI'",
                                                                 "IKC QarDuS",
                                                                 "IKC QarHIch",
                                                                 "IKC QarmIn",
                                                                 "IKC QarnuH",
                                                                 "IKC Qarpeng",
                                                                 "IKC Qaw'wI'",
                                                                 "IKC QeHtIn",
                                                                 "IKC QeHwI'",
                                                                 "IKC QemwI'",
                                                                 "IKC QengwI'",
                                                                 "IKC QeSwI'",
                                                                 "IKC QIchwI'",
                                                                 "IKC QIjbaS",
                                                                 "IKC QIjcha",
                                                                 "IKC QIjHegh",
                                                                 "IKC QIjHo'",
                                                                 "IKC QIjmaS",
                                                                 "IKC QIjram",
                                                                 "IKC QImwI'",
                                                                 "IKC Qo'bup",
                                                                 "IKC Qochbe'wI'",
                                                                 "IKC Qo'Dogh",
                                                                 "IKC Qo'Doy'",
                                                                 "IKC Qo'Duy'",
                                                                 "IKC Qo'Haj",
                                                                 "IKC Qo'Haw'",
                                                                 "IKC Qo'Hegh",
                                                                 "IKC Qo'jegh",
                                                                 "IKC Qo'joD",
                                                                 "IKC Qo'jot",
                                                                 "IKC Qo'leS",
                                                                 "IKC Qo'lIm",
                                                                 "IKC Qo'lobHa'",
                                                                 "IKC Qo'lum",
                                                                 "IKC QolwI'",
                                                                 "IKC Qo'magh",
                                                                 "IKC Qo'meQ",
                                                                 "IKC Qo'moS",
                                                                 "IKC Qo'ngeD",
                                                                 "IKS Qo'noS Wa'",
                                                                 "IKC Qo'Qagh",
                                                                 "IKC Qo'QIv",
                                                                 "IKC Qo'SaH",
                                                                 "IKC Qo'SIH",
                                                                 "IKC Qo'tlheD",
                                                                 "IKC Qo'tor",
                                                                 "IKC Qo'tun",
                                                                 "IKC Qo'tuv",
                                                                 "IKC Qo'yon",
                                                                 "IKC QughwI'",
                                                                 "IKC Quin'lat",
                                                                 "IKC Qui'Tu",
                                                                 "IKC QuprIp",
                                                                 "IKC QuQlaH",
                                                                 "IKC QuQngat",
                                                                 "IKC QuQ'oy'",
                                                                 "IKC QuQqaD",
                                                                 "IKC QuQSogh",
                                                                 "IKC QuQvaj",
                                                                 "IKC QuQveS",
                                                                 "IKC QuQvI'",
                                                                 "IKC Qutbe'",
                                                                 "IKC QutHol",
                                                                 "IKC Qutqempa'",
                                                                 "IKC QutSa'",
                                                                 "IKC Qu'Vat",
                                                                 "IKC Ro'kegh",
                                                                 "IKC Rotarran",
                                                                 "IKC SeHwI'",
                                                                 "IKC SepwI'",
                                                                 "IKS Slivin",
                                                                 "IKS Somraw",
                                                                 "IKC Sto'Vo'Kor",
                                                                 "IKC SuDwI'",
                                                                 "IKC T'Acog",
                                                                 "IKC Ta'wI'",
                                                                 "IKC TaymoHwI'",
                                                                 "IKC TlheDwI'",
                                                                 "IKC Toh'Kaht",
                                                                 "IKS T'Ong",
                                                                 "IKC VangwI'",
                                                                 "IKC VaQbach",
                                                                 "IKC VaQDoch",
                                                                 "IKC VaQDol",
                                                                 "IKC VaQDup",
                                                                 "IKC VaQpeng",
                                                                 "IKC VaQto'",
                                                                 "IKC VaQwI'",
                                                                 "IKC VaQyaS",
                                                                 "IKC VerghwI'",
                                                                 "IKC VI'wI'",
                                                                 "IKC VorcaS",
                                                                 "IKC Vor'cha",
                                                                 "IKC Vorn",
                                                                 "IKC Vornak",
                                                                 "IKC Yavang",
                                                                 "IKS Y'tem",
                                                                 "IKC YotwI' "
                                                             };
        #endregion
    }
}
